### ISSUE TITLE
error while running EPA-ng

### ISSUE THREAD

**Issue by cooketho** [ebi-pf-team/treegrafter#4]
After commenting out the section of code I mentioned in https://github.com/ebi-pf-team/treegrafter/issues/3, I tried running treegrafter on a toy data set contained in bla.fa:

```
>Cyanophora_paradoxa_CPAR027107_Apc11_1
QKTLTILAKDRNYKVEDFKAAGAIAKTRLDQQREPCSCKVAASDAHPCVRRVLFLNLSAA
VGAREPRLGARRAPALRSMKVKIVWHAVASWTWNVDDEACGICRNAYDGCCPDCKTPGDD
CPLWGECRHAFHLHCILKWVNSQQEG
>Cyanophora_paradoxa_CPAR027107_Apc11_2
REPCSCKVAASDAHPCVRRVLFLNLSAA
VGAREPRLGARRAPALRSMKVKIVWHAVASWTWNVDDEACGICRNAYDGCCPDCKTPGDD
CPLWGECRHAFHLHCILKWVNSQQEGKQHCPMCRRDWKFRSSD
>Cyanophora_paradoxa_CPAR027107_Apc11_3
QKTLTILAKDRNYKVEDFKAAGAIAKTRLDQQREPCSCKVAASDAHPCVRRVLFLNLSAA
VGAREPRLGARRAPALRSMKVKIVWHAVASWTWNVDDEACGICRNAYDGCCPDCKTPGDD
CPLWGECRHAFHL
```
First I ran hmmsearch, which went fine:
```
hmmsearch \
/home/tom/PANTHER16.0_data/famhmm/binHmm \
bla.fa \
> bla.out
```

But now I get an error running this command:
```
python treegrafter.py \
bla.fa \
bla.out \
/home/tom/PANTHER16.0_data  \
> bla.treegrafter.out \
-T temp \
--keep
```

```
error while running EPA-ng: epa-ng -G 0.05 -m WAG -T 1 -t /home/tom/PANTHER16.0_data/Tree_MSF/PTHR11210.bifurcate.newick -s /home/tom/panther/PANTHER16.0_data/Tree_MSF/PTHR11210.AN.fasta -q temp/tmp_jhftu2i/PTHR11210_query.fasta -w temp/tmp_jhftu2i/PTHR11210_epang
```

After re-running that command manually using --redo, I get the message:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  temp/tmp_jhftu2i/PTHR11210_query.fasta does not contain equal size sequences! First offending sequence: Cyanophora_paradoxa_CPAR027107_Apc11_1
Aborted (core dumped)
```

The temp file in question looks like this:

```
>Cyanophora_paradoxa_CPAR027107_Apc11_2
------------MKVKI-VWHAVASWTWNVDDEACGICRNAYDGCCPDCK-TPG---DDCPL-WGECRHAFHLHCILKWV
NSQ------
>Cyanophora_paradoxa_CPAR027107_Apc11_1
-----------SMKVKI-VWHAVASWTWNVDDEACGICRNAYDGCCPDCK-TPG---DDCPL-WGECRHAFHLHCILKWV
NS------------------
>Cyanophora_paradoxa_CPAR027107_Apc11_3
-----------SMKVKI-VWHAVASWTWNVDDEACGICRNAYDGCCPDCK-TPG---DDCPL-WGECRHAFHL-------
----------------------
```

Is it supposed to have equal-length sequences? Can you please tell me what might be going wrong? Thanks!

I'm using epa-ng 0.3.8 from here:
conda install -c bioconda epa-ng

**Comment by tgrego** [comment]
The query sequences can be anything you want (different sizes).
For each sequence we find the best tree (PANTHER family) using HMMER.
Then the query sequence needs to be aligned and cropped to basically fit in the MSA file for that family.
That aligned sequence is what we call the query_msa, and that is why it needs to be the exact size of what we call the pthr_align_length (this is the length of the sequences in the MSA file).

This is a requirement of both EPA-ng and RAxML-EPA...
